#!/usr/bin/env python3
"""Generate esp32/src/cpu9900.cpp from Classic99's console/cpu9900.cpp.

Keeps Tursi's opcode implementations verbatim and only rewrites the Win32,
F18A-GPU, debugger and big-table parts. Re-run after pulling upstream changes.
"""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]
src = (root / "console" / "cpu9900.cpp").read_text(encoding="latin-1").splitlines()


def find(prefix, start=0):
    for i in range(start, len(src)):
        if src[i].startswith(prefix):
            return i
    sys.exit(f"pattern not found: {prefix}")


ops_end = find("void CPU9900::op_norm()")          # debug + F18 opcodes start here
build_start = find("void CPU9900::buildcpu()")
build_end = find("///// F18A implementation")

text = "\n".join(src[:ops_end] + src[build_start:build_end])

# headers / externs
text = text.replace('#define WIN32_LEAN_AND_MEAN\n#define _WIN32_WINNT 0x0501\n#include <stdio.h>\n#include <windows.h>\n#include <vector>\n#include "tiemul.h"\n#include "cpu9900.h"\n#include "..\\addons\\F18A.h"\n#include "..\\resource.h"',
                    '#include <stdio.h>\n#include <esp_attr.h>\n#include "ti_types.h"\n#include "bus.h"\n#include "cpu9900.h"')
text = re.sub(r"extern bool BreakOnIllegal;.*?extern CRITICAL_SECTION csDisasm;\n", "", text, flags=re.S)

# byte/word wrappers are inline in the ESP32 header
text = re.sub(r"Byte CPU9900::RCPUBYTE\(Word src\) \{.*?\nvoid CPU9900::WRWORD\(Word dest, Word val\) \{\n    wrword\(dest, val\);\n\}\n", "", text, flags=re.S)

# reset: no F18A flash
text = text.replace("    spi_reset();                            // reset the F18A flash interface\n", "")

# interrupt: drop disassembly logging block
text = re.sub(r"    // debug helper if logging\n    EnterCriticalSection\(&csDisasm\);.*?LeaveCriticalSection\(&csDisasm\);\n", "", text, flags=re.S)

# MSVC integer types
text = text.replace("unsigned __int32", "uint32_t").replace("__int32", "int32_t")

# single emulation task: plain integer cycle counting
text = text.replace("InterlockedExchange((LONG*)&nCycleCount, 0);", "nCycleCount = 0;")
text = text.replace("InterlockedExchangeAdd((LONG*)&nCycleCount, val);", "nCycleCount += val;")
text = text.replace("InterlockedExchange((LONG*)&nCycleCount, x);", "nCycleCount = x;")

# 64K word status table -> computed
text = text.replace("Word WStatusLookup[64*1024];\n", "")
text = re.sub(r"WStatusLookup\[([^\]]+)\]", r"wstatus(\1)", text)
text = re.sub(r"\n    // build the Word status lookup table\n    for \(i=0; i<65536; i\+\+\) \{.*?\n    \}\n", "\n", text, flags=re.S)

# 64K member-function table -> 4K byte index + small function table
text = text.replace("CALL_MEMBER_FN(this, opcode[in])();", "CALL_MEMBER_FN(this, opFns[opIndex[in>>4]])();")
text = re.sub(r"opcode\[in\]=(&CPU9900::op_\w+);", r"setOp(in, \1);", text)
text = text.replace("    for (i=0; i<65536; i++)\n    { \n        in=(Word)i;",
                    "    opCount = 0;\n    for (i=0; i<65536; i+=16)\n    { \n        in=(Word)i;")
text = re.sub(r"\n    // check for special debug opcodes\n    if \(enableDebugOpcodes\) \{.*?\n    \}\n", "\n", text, flags=re.S)

# illegal opcode: no Win32 yield, no debugger
text = text.replace("    SwitchToThread();           // these have a habit of taking over the emulator in crash situations :)\n", "")
text = text.replace("    if (BreakOnIllegal) TriggerBreakPoint();\n", "")

# hot path in IRAM: decode, address calculation, interrupts and every opcode (~12K)
for fn in ("Word CPU9900::ExecuteOpcode", "void CPU9900::fixS()", "void CPU9900::fixD()",
           "void CPU9900::TriggerInterrupt", "void CPU9900::parity"):
    text = text.replace(fn, "IRAM_ATTR " + fn, 1)
text = re.sub(r"^void CPU9900::op_", "IRAM_ATTR void CPU9900::op_", text, flags=re.M)
text = text.replace("IRAM_ATTR void CPU9900::op_bad", "void CPU9900::op_bad")

text += """

// maps one 16-opcode group (low 4 bits are operands) to a shared function slot
void CPU9900::setOp(Word in, CPU990Fctn fn)
{
    int k;
    for (k=0; k<opCount; k++) {
        if (opFns[k] == fn) break;
    }
    if (k == opCount) {
        if (opCount >= MAX_OPFNS) {
            debug_write("opFns table full");
            return;
        }
        opFns[opCount++] = fn;
    }
    opIndex[in>>4] = (uint8_t)k;
}
"""

header = ("// GENERATED by esp32/tools/port_cpu.py from console/cpu9900.cpp - do not edit by hand.\n"
          "// Changes: compact opcode decode, computed word status, no Win32/F18A GPU/debugger.\n")
leftovers = [w for w in ("windows.h", "InterlockedExchange", "CriticalSection", "WStatusLookup", "opcode[", "TriggerBreakPoint", "SwitchToThread", "fpDisasm")
             if w in text]
if leftovers:
    sys.exit(f"untranslated Win32/table code left: {leftovers}")

out = root / "esp32" / "src" / "cpu9900.cpp"
out.write_text(header + text + "\n", encoding="utf-8")
print(f"wrote {out} ({text.count(chr(10))} lines)")
